### PR TITLE
Include identifier in error message when finding non-alphanumeric chars

### PR DESCRIPTION
**Pull request by dfaust**
Small improvement that makes it more obvious where the cause of the error lies.

### CODE REVIEW

**Comment by dwrensha** [comment]
This change looks good to me, but I'm curious: did you manage to trigger these errors when compiling a capnp schema? I would expect that `capnp compile` would catch the non-alphanumeric identifiers before passing them to `capnpc-rust`.

**Comment by dfaust** [comment]
Yes, I hit the one in `camel_to_snake_case` because I had an argument for a method formatted in snake case instead of camel case.

**Comment by dwrensha** [comment]
Interesting! I've opened as issue upstream: https://github.com/capnproto/capnproto/issues/506

**Comment by dwrensha** [comment]
Thanks!

**Pull request merged**
